@startuml diag1
class general {}

class client <<general>> {
}
client <|-- general

class route <<general>> {
}
route <|-- general

class voucher <<general>> {
}
voucher <|-- general
voucher *-- client
voucher *-- routeList

class generalList {
}  

class clientList <<generalList>> {
}
clientList <|-- generalList
clientList o-- client 

class routeList <<generalList>> {
}
routeList <|-- generalList
routeList o-- route

class voucherList <<generalList>> {
}
voucherList <|-- generalList
voucherList o-- voucher

class company {
}
company *-- voucherList
company *-- clientList
company *-- routeList

@enduml